spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 88888888
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai

rpc:
  center:
    active: true
    connectStr: 47.96.43.26:2181
    sessionTimeoutMs: 50000
    connectionTimeoutMs: 50000
